#....... .. .       .   .           . DDDN      .............
#.....    . .                  .   DNDDDD$    . .............
#...   .. ....  .. ........ .. ..$DDDDDDD  .. ...............
#... ... ....                   NDDDDDDDD       .............
#...   ...... .. . .. ... .  ..NDDDDDDDD..  ... .............
#......  .... . .... ...  .....DDDDDDDN  .... ...............
#...     .. .                 ODDDDDD.          .............
#...   . ....                 NDDDN..           .............
#...  .   ...    .  ~O+..           ..:MDDD...  .............
#..... . .. . ..DDDDDDDDDDND.   ..NDDDDDDDDDDDNO.............
#... ..  ....NDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDM...........
#...      ..DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD..........
#...   . .=DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD...........
#...    ..DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDN............
#... . ..NDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD..............
#...    $DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDO .............
#...  ..DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD. .............
#...    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD  .............
#...   .DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD  .............
#... . .DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD  .............
#... . .DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD...............
#... ...DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD? .............
#...    NDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD..............
#...   . DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD~............
#... .  .NDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD ..........
#...     .DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.........
#... . . .DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDN........
#... . . ..DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD ........
#... . . ...DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD..........
#...........?DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD7..........
#............ZDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD$...........
#.............,DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDI........ . .
#...............DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD .  . .    .. 
#................DDDDDDDDDDDDDNNNDNDDDDDDDDDDD..   .  .  .  .
#..................DDDDDDN..........,NDDDDDN ......  ....... 
# This plugin is made and approved by AppleNick
# Jarvis - Alpha Edition

#Your FULL user name for Jarvis
userFull: applenick3

# Enter what you want Jarvis to change your DisplayName to and refer to you as
nick: &4Apple

# This will be a keyword for Jarvis to authenticate you with
pass: Apples